---
apiVersion: v1
kind: Pod
metadata:
  name: myspl-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-pod-config
      image: mysql:8
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: mysql-config
            optional: false
      volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-vol
    
