---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-secreat
  labels:
    app: mysql
spec:
  containers:
    - name: my-secreat-pod
      image: mysql:8
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: mysql-secreat
            optional: false
      volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-vol               