---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-template
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.23
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP  
  ports:
    - name: nginx-port
      port: 80
      protocol: TCP
      targetPort: 80                                   