---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxreplica
  labels:
    app: nginx
    layers: web
    version: "1.23"  
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: "1.23"
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80        