---
apiVersion: v1
kind: Service
metadata:
  name: mysql-head-svc
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: headless
      port: 3306
      protocol: TCP  