---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pvc
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

        