---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  minReadySeconds: 4
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-head-svc"
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: mysql
            - name: MYSQL_USER
              value: laxman
            - name: MYSQL_PASSWORD
              value: rootroot 
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql
      volumes: 
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc                     