---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetjob
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      name: podreplica
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxpod
          image: nginx:1.23
          ports:
            - containerPort: 80  
