---
apiVersion: v1
kind: Pod
metadata:
  name: noppod
  labels:
    app: nop
spec:
  containers:
    - name: nop
      image: lakshminarayana1849/nopcommerse
      ports:
        - containerPort: 5000
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: laxman
        - name: MYSQL_USER
          value: laxman
        - name: MYSQL_PASSWORD
          value: laxman
        - name: MYSQL_DATABASE
          value: employees
      volumeMounts:
        - name: my-volume
          mountPath: /var/lib/mysql
  volumes:
    - name: my-volume