---
apiVersion: v1
kind: Service
metadata:
  name: nop-regular-svc
spec:
  selector:
    app: nop
  ports:
    - name: nop-svc
      port: 35000
      targetPort: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nopdeployment
  labels:
    app: nop
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      app: nop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      name: nop-pod
      labels:
        app: nop
    spec:
      containers:
        - name: nop
          image: lakshminarayana1849/nopcommerse
          ports:
            - containerPort: 5000

  