---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load
spec:
  ports:
    - name: https
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx    
  type: LoadBalancer    