---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetjob
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels: 
      app: alpine
  template:
    metadata:
      name: podreplica
      labels:
        app: alpine
    spec:
      containers:
        - name: alpinepod
          image: 266634946728.dkr.ecr.ap-south-1.amazonaws.com/alpine
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred         