---
apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
spec:
  containers:
    - name: mysql
      image: mysql:8
      envFrom:
        - configMapRef:
            name: configmap-demo
            optional: false
      ports:
        - containerPort: 3306     
