---
apiVersion: v1
kind: Pod
metadata:
  name: initpod-demo
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
  initContainers:
    - name: delay
      image: alpine
      command:
        - sleep
        - 10s
    - name: init-myservice
      image: busybox:1.28
      command: 
        - 'sh'
        - '-c'
        - "until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"      