---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  minReadySeconds: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      - name: nginxreplica
        labels:
          app: web
    spec:
      containers:
        - name: nginxpod
          image: nginx
          ports:
            - containerPort: 80        

          